version: "3.9"

services:

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    env_file: .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    container_name: server
    image: server
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        SERVER_PORT: ${SERVER_PORT}
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      SERVER_PORT: ${SERVER_PORT}
    depends_on:
      postgres:
        condition: service_healthy

  client:
      container_name: client
      image: client
      env_file: .env
      build:
          context: .
          dockerfile: Dockerfile.client
          args:
            CLIENT_PORT: ${CLIENT_PORT}
      restart: always
      ports:
          - "${CLIENT_PORT}:80"
      environment:
        - CLIENT_PORT=${CLIENT_PORT}
        - SERVER_PORT=${SERVER_PORT}
      depends_on:
        - server

