version: "3"

services:

    postgres:
      extends:
        file: docker-compose.yml
        service: postgres

    pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      env_file: .env
      environment:
        - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
        - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      ports:
        - "${PGADMIN_PORT}:80"
      depends_on:
        - postgres
